version: "3.7"
services:

  breath_dev:
    build:
      context: ./
    image: breath
    volumes:
        - ./breath.yml:/root/app/breath.yml
    #entrypoint: bash init-start.sh
    restart: on-failure
    network_mode: host
    cap_add: [ NET_ADMIN ]
